[package]
name = "chemistry-core"
version.workspace = true
edition.workspace = true

[features]
default = []
long-experiments = []

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
image = { workspace = true }
